version: '3.1'

#If this network is not already created, run docker create nest-net before running docker-compose
networks:
  nest-net:
      external: true

services:
  nest_server:
      container_name: server
      image: quaffpotion/nest-crud
      networks:
          - nest-net
      ports:
          - 3000:3000

  db_service:
    container_name: db
    image: postgres:11
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: db_user
        POSTGRES_PASSWORD: db_password
        POSTGRES_DB: db_app
        PGPORT: 5432
    networks:
        - nest-net

  adminer_service:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
        - nest-net
